global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'stock_metrics'
    metrics_path: '/api/stock-price-metrics/'
    static_configs:
      - targets: ['web:8000']

# rule_files:
#   - 'alerts.yml'
