name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Adjust this based on your branching strategy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate .env file
        run: |
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" > .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sayalisa2li7/backend_techdemo:${{ github.sha }}

      - name: Output Docker Image Tag
        run: |
          echo "Image tag: sayalisa2li7/backend_techdemo:${{ github.sha }}"

      - name: Update Helm Chart with New Image Tag
        run: |
          sed -i "s/tag2: .*/tag2: '${{ github.sha }}'/" helm-tech-demo/techdemo/values.yaml

      - name: Commit Updated Helm Chart
        run: |
          git config --local user.email "sayalis0910@gmail.com"
          git config --local user.name "sayali shinde"
          git add helm-tech-demo/techdemo/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
